services:
  google-mcp:
    build: .
    container_name: google-mcp
    env_file:
      - .env
    volumes:
      - ./.google:/app/.google
    ports:
      - "8086:8086"
    networks:
      - npm_default

networks:
  npm_default:
    external: true
